---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: spr-sa
roleRef:
  kind: Role
  name: secret-pod-reader