---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-pod-reader
rules:
  - apiGroups: ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
  - apiGroups: ""
    resources:
      - pod
    verbs:
      - get
      - watch
      - list