---
apiVersion: v1
kind: Service
metadata:
  name: nop-svc
  namespace: activity1
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: nop
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80